### ISSUE TITLE
[BUG] Quadradius not loading

### ISSUE THREAD

**Issue by pyite76** [Fruktus/QuadradiusPreservationProject#106] opened 2024-05-23 14:26 UTC
### Affected platform

Launcher

### Describe the bug

Says the file might be removed?

### Expected behavior

Should load the game

**Comment by kjarosh** [comment] 2024-05-23 14:39
Hi, thank you for the report!

I've checked it on my system and it generally works, so I have some follow up questions:

1. What platform do you use? (Windows / Linux / MacOS)
2. How did you install the launcher?
3. What were you trying to do before the error appeared (i.e. how to reproduce it)?

You might also want to include some screenshots so that we're able to reproduce it better.

**Comment by pyite76** [comment] 2024-05-23 15:26
1. Windows
2. I can't remember
3. load the game

[image: image.png]

[image: image.png]
[image: image.png]

[image: image.png]

**Comment by Fruktus** [comment] 2024-05-23 20:06
Hi, thank you for the report. I am trying to reproduce the error.
1. I downloaded the latest launcher release for windows [quadradius-launcher-win32-x64-1.1.0.zip](https://github.com/Fruktus/QuadradiusPreservationProject/releases/download/v1.2.0/quadradius-launcher-win32-x64-1.1.0.zip)
2. I unpacked it and ran ```quadradius-launcher.exe```
3. I entered server address ```quadradius.ddns.net``` and connected
4. 
The game loaded normally and I was able to start the match. If possible please let me know if any of these steps differ from what you did, since right now I don't really know where to look. As a side note, it seems that the images didn't  upload correctly :/

**Comment by Fruktus** [comment] 2024-09-03 14:15
I'm closing the issue due to lack of further information

**Closed by Fruktus** 2024-09-03 14:15 UTC
Labels: bug
